import type { PayloadRequest } from 'payload'

/**
 * Endpoint that returns robots.txt content for AI discoverability.
 * Site owners should append this to their robots.txt or use the
 * generated text directly.
 *
 * GET /api/scrape-ai/robots-txt → returns the text to add
 */
export function createRobotsTxtEndpoint(siteUrl: string) {
  return {
    path: '/scrape-ai/robots-txt',
    method: 'get' as const,
    handler: async (req: PayloadRequest) => {
      const robotsTxt = [
        '# AI Content Discovery',
        '# Generated by payload-plugin-scrape-ai',
        '',
        '# AI content index files',
        `Sitemap: ${siteUrl}/ai/sitemap.json`,
        '',
        'User-agent: *',
        'Allow: /llms.txt',
        'Allow: /llms-full.txt',
        'Allow: /ai/',
        'Allow: /.well-known/ai-plugin.json',
        '',
        `# AI content entry point: ${siteUrl}/llms.txt`,
        `# Full content listing: ${siteUrl}/llms-full.txt`,
        `# Discovery manifest: ${siteUrl}/.well-known/ai-plugin.json`,
      ].join('\n')

      return new Response(robotsTxt, {
        status: 200,
        headers: { 'Content-Type': 'text/plain; charset=utf-8' },
      })
    },
  }
}
